// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hnoocwhgvhdccmcfjstq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhub29jd2hndmhkY2NtY2Zqc3RxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5MDYwODYsImV4cCI6MjA1NjQ4MjA4Nn0.37bw7A-0TteyA-hUQApAIPchRIItCj7dKZrLJL2cG_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);